#############################################
# Menu docs
#############################################

##################
## Getting started section
##################

[[docs]]
  name = "Getting started"
  weight = 10
  identifier = "docs-getting-started"

[[docs]]
  name = "Unpack Reachy 2"
  weight = 100
  parent = "docs-getting-started"
  url = "/docs/getting-started/unpack/"

[[docs]]
  name = "Safety guidelines"
  weight = 110
  parent = "docs-getting-started"
  url = "/docs/getting-started/safety/"

[[docs]]
  name = "Start your robot"
  weight = 120
  parent = "docs-getting-started"
  url = "/docs/getting-started/turn-on/"

[[docs]]
  name = "Connect your robot to the network"
  weight = 130
  parent = "docs-getting-started"
  url = "/docs/getting-started/network/"

[[docs]]
  name = "Connect to the dashboard"
  weight = 140
  parent = "docs-getting-started"
  url = "/docs/getting-started/dashboard/"

[[docs]]
  name = "Hello world"
  weight = 150
  parent = "docs-getting-started"
  url = "/docs/getting-started/hello-world/"

[[docs]]
  name = "Stop your robot"
  weight = 160
  parent = "docs-getting-started"
  url = "/docs/getting-started/turn-off/"

##################
## Simulation section
##################

[[docs]]
  name = "Simulation"
  weight = 20
  identifier = "docs-simulation"

[[docs]]
  name = "Simulation installation"
  weight = 200
  parent = "docs-simulation"
  url = "/docs/simulation/simulation-installation/"

##################
## Update section
##################

[[docs]]
  name = "Update Reachy 2"
  weight = 30
  identifier = "docs-update"

[[docs]]
  name = "Update Reachy 2 software"
  weight = 300
  url = "/docs/update/update"
  parent = "docs-update"

##################
## Advanced section
##################

[[docs]]
  name = "Advanced"
  weight = 40
  identifier = "docs-advanced"

[[docs]]
  name = "Access Reachy 2 computer"
  weight = 400
  url = "/docs/advanced/access-computer"
  parent = "docs-advanced"

[[docs]]
  name = "Calibrate teleop cameras"
  weight = 410
  url = "/docs/advanced/calibrate-cameras"
  parent = "docs-advanced"

#############################################
# Menu dashboard
#############################################

#######################
## Introduction section
#######################

[[dashboard]]
  name = "Introduction"
  weight = 10
  identifier = "dashboard-introduction"

[[dashboard]]
  name = "Introduction"
  weight = 100
  parent = "dashboard-introduction"
  url = "/dashboard/introduction/introduction/"

[[dashboard]]
  name = "Connection"
  weight = 110
  parent = "dashboard-introduction"
  url = "/dashboard/introduction/connection/"

#######################
## Content section
#######################

[[dashboard]]
  name = "Content"
  weight = 20
  identifier = "dashboard-content"

[[dashboard]]
  name = "Services"
  weight = 200
  parent = "dashboard-content"
  url = "/dashboard/content/services/"

[[dashboard]]
  name = "Network"
  weight = 210
  parent = "dashboard-content"
  url = "/dashboard/content/network/"

[[dashboard]]
  name = "Updates"
  weight = 220
  parent = "dashboard-content"
  url = "/dashboard/content/updates/"

[[dashboard]]
  name = "Visualization tools"
  weight = 230
  parent = "dashboard-content"
  url = "/dashboard/content/visualization/"

[[dashboard]]
  name = "Reachy control"
  weight = 240
  parent = "dashboard-content"
  url = "/dashboard/content/dashboard/"

#############################################
# Menu SDK
#############################################

##################
## Getting started section
##################

[[sdk]]
  name = "Introduction"
  weight = 10
  identifier = "sdk-introduction"

[[sdk]]
  name = "Introduction"
  weight = 100
  parent = "sdk-introduction"
  url = "/sdk/introduction/introduction"

##################
## Getting started section
##################

[[sdk]]
  name = "Getting started"
  weight = 20
  identifier = "sdk-getting-started"

[[sdk]]
  name = "Installation"
  weight = 200
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/install"

[[sdk]]
  name = "Connect to Reachy 2"
  weight = 210
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/connect"

[[sdk]]
  name = "Hello World"
  weight = 220
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/hello-world"

[[sdk]]
  name = "SDK Overview"
  weight = 230
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/overview"

[[sdk]]
  name = "Safety first"
  weight = 240
  parent = "sdk-getting-started"
  url = "/sdk/getting-started/safety"

##################
## First moves section
##################

[[sdk]]
  name = "First moves"
  weight = 30
  identifier = "sdk-first-moves"

[[sdk]]
  name = "1. Start with Reachy 2"
  weight = 300
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/intro"

[[sdk]]
  name = "2. Understand moves in Reachy 2"
  weight = 310
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/moves"

[[sdk]]
  name = "3. Basic arm control"
  weight = 320
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/arm"

[[sdk]]
  name = "4. Use arm kinematics"
  weight = 330
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/kinematics"

[[sdk]]
  name = "5. Control the head"
  weight = 340
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/head"

[[sdk]]
  name = "6. Get images from cameras"
  weight = 350
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/cameras"

[[sdk]]
  name = "7. Record and replay trajectories"
  weight = 360
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/record"

[[sdk]]
  name = "8. Use the mobile base"
  weight = 370
  parent = "sdk-first-moves"
  url = "/sdk/first-moves/mobile-base"

##################
## Advanced section
##################

[[sdk]]
  name = "Advanced"
  weight = 40
  identifier = "sdk-advanced"

[[sdk]]
  name = "Mobile base modes"
  weight = 400
  parent = "sdk-advanced"
  url = "/sdk/advanced/mobile-base"

#############################################
# Menu main - add parts to main page nav menu here!
#############################################

[[main]]
  name = "Setup Reachy 2"
  url = "/docs/getting-started/unpack/"
  weight = 10

[[main]]
  name = "Python SDK"
  url = "/sdk/introduction/introduction/"
  weight = 20

[[main]]
  name = "Teleoperation"
  url = "/vr/introduction/introduction/"
  weight = 30

[[main]]
  name = "Dashboard"
  weight = 40
  url = "/dashboard/introduction/introduction/"

[[main]]
  name = "Help"
  weight = 50
  url = "/help/help/recovering/"

#############################################
# Menu VR
#############################################

##################
## Intro section
##################

[[vr]]
  name = "Introduction"
  weight = 10
  identifier = "vr-introduction"

[[vr]]
  name = "Introduction"
  weight = 100
  parent = "vr-introduction"
  url = "vr/introduction/introduction"

##################
## Compatibility section
##################

[[vr]]
  name = "Compatibility"
  weight = 20
  identifier = "vr-compatibility"

[[vr]]
  name = "Compatible headsets"
  weight = 200
  parent = "vr-compatibility"
  url = "vr/compatibility/headsets"

[[vr]]
  name = "PC requirements"
  weight = 210
  parent = "vr-compatibility"
  url = "vr/compatibility/pc-requirements"

##################
## Getting started section
##################

[[vr]]
  name = "Getting started"
  weight = 30
  identifier = "vr-getting-started"

[[vr]]
  name = "Installation"
  weight = 300
  parent = "vr-getting-started"
  url = "vr/getting-started/installation"

[[vr]]
  name = "Check robot is ready"
  weight = 310
  parent = "vr-getting-started"
  url = "vr/getting-started/check-robot"

[[vr]]
  name = "Connect to Reachy 2"
  weight = 320
  parent = "vr-getting-started"
  url = "vr/getting-started/connect"

[[vr]]
  name = "Setup your teleop session"
  weight = 330
  parent = "vr-getting-started"
  url = "vr/getting-started/setup"

##################
## Using section
##################

[[vr]]
  name = "Using the app"
  weight = 40
  identifier = "vr-use"

[[vr]]
  name = "🚨 Best practice"
  weight = 400
  parent = "vr-use"
  url = "vr/use-teleop/best-practice"

[[vr]]
  name = "Controllers inputs"
  weight = 410
  parent = "vr-use"
  url = "vr/use-teleop/commands"

[[vr]]
  name = "Teleoperate Reachy"
  weight = 430
  parent = "vr-use"
  url = "vr/use-teleop/start"

[[vr]]
  name = "Teleoperation messages"
  weight = 440
  parent = "vr-use"
  url = "vr/use-teleop/messages"

##################
## Problem section
##################

[[vr]]
  name = "Problem"
  weight = 50
  identifier = "vr-problem"

[[vr]]
  name = "Debug"
  weight = 500
  parent = "vr-problem"
  url = "vr/problem/debug"

[[vr]]
  name = "Support"
  weight = 510
  parent = "vr-problem"
  url = "vr/problem/support-vr"

#############################################
# Menu help
#############################################

################
## Help Section
################

[[help]]
  name = "Help"
  weight = 10
  identifier = "help-debug"

[[help]]
  name = "Recovering"
  weight = 100
  parent="help-debug"
  url = "/help/help/recovering/"

[[help]]
  name = "Debug"
  weight = 110
  parent="help-debug"
  url = "/help/help/debug/"

[[help]]
  name = "Hardware intervention"
  weight = 120
  parent="help-debug"
  url = "/help/help/torso/"

[[help]]
  name = "Support"
  weight = 130
  parent="help-debug"
  url = "/help/help/support/"

#################
## System section
#################

[[help]]
  name = "System"
  weight = 20
  identifier = "help-system"

[[help]]
  name = "Finding Reachy 2's IP"
  weight = 200
  parent="help-system"
  url = "/help/system/find-my-ip/"

#################
## Safety section
#################

[[help]]
  name = "Safety"
  weight = 30
  identifier = "help-safety"

[[help]]
  name = "Use Reachy 2 properly"
  weight = 300
  parent="help-safety"
  url = "/help/safety/correct-use/"

[[help]]
  name = "Use VR teleoperation"
  weight = 310
  parent="help-safety"
  url = "/help/safety/vr-use/"

#############################################
[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/pollenrobotics"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/pollen-robotics/"
  post = "v0.1.0"
  weight = 20


